/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QRSDetectGUI.java
 *
 * Created on 19 Jul 09, 14:53:07
 */
package ecgChart;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;

import java.awt.geom.Point2D;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
//import java.io.IOException;
import javax.swing.JFileChooser;
//import ECGInterpretation.*;

import ECGInterpretation.DownSampling;



/**
 *
 * @author AULIAN ARIF
 */
public class MainGUI extends javax.swing.JFrame {

    /** Creates new form QRSDetectGUI */
    public MainGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        analyzeButton = new javax.swing.JButton();
        recordButton = new javax.swing.JButton();
        pasienButton = new javax.swing.JButton();
        headerLabel = new javax.swing.JLabel();
        fileLabel = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        exitMenuItem = new javax.swing.JMenuItem();
        toolMenu = new javax.swing.JMenu();
        readMenuItem = new javax.swing.JMenuItem();
        plotMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interpretasi ECG");

        analyzeButton.setIcon(new javax.swing.ImageIcon("icon/colba_64.png")); // NOI18N
        analyzeButton.setText("Analisis Pradiagnosa");
        analyzeButton.setToolTipText("Pra-diagnostic Analysis");
        analyzeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        analyzeButton.setIconTextGap(10);

        recordButton.setIcon(new javax.swing.ImageIcon("icon/heart_64.png")); // NOI18N
        recordButton.setText("Rekam Data ECG");
        recordButton.setToolTipText("Records patients ECG data");
        recordButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recordButton.setIconTextGap(10);
        recordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordButtonActionPerformed(evt);
            }
        });

        pasienButton.setIcon(new javax.swing.ImageIcon("icon/case_64.png")); // NOI18N
        pasienButton.setText("Data Pasien");
        pasienButton.setToolTipText("Patient's data");
        pasienButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pasienButton.setIconTextGap(10);

        headerLabel.setText("Data Pasien :");

        fileLabel.setText("ECG File :");

        fileMenu.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);
        fileMenu.add(jSeparator1);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        mainMenuBar.add(fileMenu);

        toolMenu.setText("Tool");

        readMenuItem.setText("Read File");
        readMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(readMenuItem);

        plotMenuItem.setText("Plot to Chart");
        toolMenu.add(plotMenuItem);

        mainMenuBar.add(toolMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(recordButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pasienButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(analyzeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(headerLabel)
                    .addComponent(fileLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasienButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analyzeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileLabel)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
         chooser = new JFileChooser(new File("SampleFile/"));

        if (evt.getSource() == openMenuItem) {
            int returnVal = chooser.showOpenDialog(MainGUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                String fileName = chooser.getSelectedFile().getName();
                fileLabel.setText("ECG File: "+ fileName);
            }
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void readMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readMenuItemActionPerformed

            // TODO add your handling code here:
    }//GEN-LAST:event_readMenuItemActionPerformed

    private void analyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed
        // TODO add your handling code here:

    		//ex = new InterpretationDialog();
            //ex.sampleFile = chooser.getSelectedFile();
            //ex.setVisible(true);
            
    }//GEN-LAST:event_analyzeButtonActionPerformed

    private void recordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed
        // TODO add your handling code here:
    }
  
	
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton analyzeButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton pasienButton;
    private javax.swing.JMenuItem plotMenuItem;
    private javax.swing.JMenuItem readMenuItem;
    private javax.swing.JButton recordButton;
    private javax.swing.JMenu toolMenu;
    private JFileChooser chooser;
    // End of variables declaration//GEN-END:variables

}
